config/routes.rb
Rails.application.routes.draw do

  get '/locations/show', to: 'locations#show', as: 'temp'
  root to: 'locations#index'
  #resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'open_weather'
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show]


  def index
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @city = params[:location]
      options = {units: "metric", APPID: "9bdfdb5ca9057942a607c6bf38ac0766"}
      @all_details = OpenWeather::Forecast.city(@city, options)
      if @all_details["city"]
        @weather = @all_details["list"][0]["main"]["temp"] 
        @weather_deatails = @all_details["list"][0]["weather"][0]
        @main = @weather_deatails["main"]
        @desc = @weather_deatails["description"]
        @icon = @weather_deatails["icon"]
        @city = @all_details["city"]["name"]
        @lon = @all_details["city"]["coord"]["lon"]
        @lat = @all_details["city"]["coord"]["lat"]
      else
        @error = @all_details["message"];
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :temp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="jumbotron">
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :temp %>
    <%= f.text_field :temp %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="search-div">
  <h1>Forecast</h1>

  <div>
    <p>Write your city name and check the weather today</p>
  </div>
  <div>
    <%= form_tag "/locations/show", :method => :get do %>
      <%= text_field_tag "location", "", placeholder: "Enter your city name"%>
      <%= submit_tag "Check Weather" %>
    <% end %>  
  </div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
 <div class='search-div'>
 <% if !@error %>
 <p>
  <strong>Today Forecast For City <%=@city%> Is:</strong>
  <br />
  <%= @weather.round %>&deg;C (<%= @main %> - <%= @desc %>)
  <%= image_tag "http://openweathermap.org/img/w/#{@icon}.png" %>
  <br />
  <small> To check what you need to wear today:
  <%= link_to "Press here", "http://www.dressbyweather.com/#{@lon}/#{@lat}" %>
  </small>
</p>

<%else%>
  <p> <%= @error %></p>
  <%end%>
<%= link_to 'Back To Search', root_path %>

</div>